### ISSUE TITLE
renew og:url tag  

### ISSUE THREAD

**Issue by minwook-shin** [kookmin-learn/kookmin-learn.github.io#14]
사소한거긴한데...og 메타태그의 url을 갱신하시면 좋을듯합니다.

`<meta property="og:url" content="https://codertimo.github.io/" />`로 되어있어서...
`<meta property="og:url" content="https://kookmin-learn.github.io/" />`로 변경하시면될거같습니다.

**Comment by codertimo** [comment]
ㅇ오옹 그걸 놓쳤구만 고마워 ㅎㅎ

**Comment by keyakoto** [comment]
꽤 늦었긴 한데 og 메타태그가 없는데 어디있는거죠?
