### ISSUE TITLE
suggestion new category :: git

### ISSUE THREAD

**Issue by minwook-shin** [kookmin-learn/kookmin-learn.github.io#15]
곧 학교에서 git을 배운다던데, 간단하게 깃으로 갓헙에 파일 올리기부터 레포에서 당겨오는것까지 사이트에 올라가면 모두에게 유용할 것 같습니다.

파이썬, 라즈베리파이, 우분투와 같이 git 매뉴도 만드는것은 어떨까요?

**Comment by codertimo** [comment]
괜찮은 생각인것 같습니다 :)
그런데 git을 편집해줄 친구를 찾아야 할것 같습니다
